### ISSUE TITLE
MED41 - ECU Request.

### ISSUE THREAD

**Issue by cauddy** [jglim/UnlockECU#19]
**ECU Name**
MED41

**Source file**
MED41.smr-d
[https://mega.nz/file/JcUyVYbR#n_x8YXVOgj7gUVqsn8ToN3m6YJedu11Im0lLKBovwV4](url)

Without a known source file, the issue will be closed as it cannot be worked on. Please note that many SMR-D files do *not* include unlocking functionality. If you are referencing a SMR-D file, ensure that the file has unlocking capabilities first.

**Additional context**
Add any other optional context about the feature request here, such as security levels, expected seed-key pairs etc.

**Checklist**
_Please delete either YES or NO depending on the checklist question_

I have checked that the requested definition does not exist in [db.json](https://github.com/jglim/UnlockECU/blob/main/UnlockECU/db.json) :  YES
_Some ECUs share a common definition, for example, the CRD3 family uses the CRD3NFZ definition, and are linked together with an [alias](https://github.com/jglim/UnlockECU/blob/bcb77faa30da1babce0aca79a2d63c99618226c2/UnlockECU/db.json#L2019). If an alias is missing, please use the "Bug Report" template instead._

**Comment by jglim** [comment]
Hello cauddy,

I've taken a look at MED41.smr-d, where I found 3 sets of key parameters. These parameters exist in db.json under different names:

https://github.com/jglim/UnlockECU/blob/013a50e1fbf775b97c806e4eec3b5bc503bb53c2/UnlockECU/db.json#L6084
https://github.com/jglim/UnlockECU/blob/013a50e1fbf775b97c806e4eec3b5bc503bb53c2/UnlockECU/db.json#L6068
https://github.com/jglim/UnlockECU/blob/013a50e1fbf775b97c806e4eec3b5bc503bb53c2/UnlockECU/db.json#L5558

I'll update these definitions to include aliases for MED41, so that it shows up properly in the search. Thanks for pointing this out!
