### ISSUE TITLE
IC172 Security Level 03

### ISSUE THREAD

**Issue by Flo354** [jglim/UnlockECU#33]
**ECU Name**
IC172

**Source file**
None

**Additional context**
Security Level 03 exists and is the same as 0D

CopData = 			0x27 0x03 
Result DataBytes = 	0x67 0x03 0x45 0x89 0x2A 0x39 0x7E 0xB3 0xB3 0x7E 

CopData = 			0x27 0x04 0x06 0x3F 0x05 0x2F 0xXX 0xXX 0xXX 0xXX 
Result DataBytes = 	0x67 0x04

=> Where 0xXX is the fixed unused part

**Comment by jglim** [comment]
Thanks!

Would you like to send in a pull request? I'd like to make sure that your name also appears on the [contributors panel](https://github.com/jglim/UnlockECU/graphs/contributors) (shown on the repo's main page) so that your work is recognized.

I believe it is sufficient to insert a definition similar to this into `db.json`, somewhere around here : https://github.com/jglim/UnlockECU/blob/7f9a5985d11df4fb18c4a86e083dc1271a9bfb5a/UnlockECU/db.json#L4743
```
  {
    "EcuName": "IC172",
    "Aliases": [],
    "AccessLevel": 3,
    "SeedLength": 8,
    "KeyLength": 8,
    "Provider": "IC172Algo1",
    "Origin": "IC172_@Feezex-@Flo354",
    "Parameters": []
  },
```

**Comment by Flo354** [comment]
I created it here: https://github.com/jglim/UnlockECU/pull/34 :)
