### ISSUE TITLE
Hi, browser, can you provide open source? Different countries have firewalls on the Internet, making access difficult.

### ISSUE THREAD

**Issue by 653310641** [jglim/UnlockECU#35]

**Comment by jglim** [comment]
The regular windows application (exe) is intended for use in internet-restricted scenarios e.g. workshops, garages. It is feature identical to the browser version and will work permanently without requiring any network access.

It will be a better solution in your situation as it is easier to distribute a self-contained exe, than a webpage. Webpages can go down anytime, but the exe will work as long as you have a copy of it, even if this project disappears. You can also consider developing your own region-specific solutions such as wechat applets or telegram bots.

The web version is simply a wrapper around the core UnlockECU library. The build system is too tightly coupled with my publishing platform, and I am not planning to spend time to untangle that.

---

Also, please consider using the description field when creating an issue instead of relying only on the title.
